export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCEDED = "REGISTER_SUCCEDED";
export const REGISTER_FAILED = "REGISTER_FAILED";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCEDED = "LOGIN_SUCCEDED";
export const LOGIN_FAILED = "LOGIN_FAILED";
