export const POST_NEWOFFER_REQUEST = "POST_NEWOFFER_REQUEST";
export const POST_NEWOFFER_SUCCEDED = "POST_NEWOFFER_SUCCEDED";
export const POST_NEWOFFER_FAILED = "POST_NEWOFFER_FAILED";

export const POST_COMPANY_PROFILE_REQUEST = "POST_COMPANY_PROFILE_REQUEST";
export const POST_COMPANY_PROFILE_SUCCEDED = "POST_COMPANY_PROFILE_SUCCEDED";
export const POST_COMPANY_PROFILE_FAILED = "POST_COMPANY_PROFILE_FAILED";

export const GET_COMPANY_PROFILE_REQUEST = "GET_COMPANY_PROFILE_REQUEST";
export const GET_COMPANY_PROFILE_SUCCEDED = "GET_COMPANY_PROFILE_SUCCEDED";
export const GET_COMPANY_PROFILE_FAILED = "GET_COMPANY_PROFILE_FAILED";

export const GET_PRIVATE_OFFERS_REQUEST = "GET_PRIVATE_OFFERS_REQUEST";
export const GET_PRIVATE_OFFERS_SUCCEDED = "GET_PRIVATE_OFFERS_SUCCEDED";
export const GET_PRIVATE_OFFERS_FAILED = "GET_PRIVATE_OFFERS_FAILED";

export const GET_OFFERS_REQUEST = "GET_OFFERS_REQUEST";
export const GET_OFFERS_SUCCEDED = "GET_OFFERS_SUCCEDED";
export const GET_OFFERS_FAILED = "GET_OFFERS_FAILED";
