export const NEWOFFER_REQUEST = "NEWOFFER_REQUEST";
export const NEWOFFER_SUCCEDED = "NEWOFFER_SUCCEDED";
export const NEWOFFER_FAILED = "NEWOFFER_FAILED";

export const GET_PRIVATE_OFFERS_REQUEST = "GET_PRIVATE_OFFERS_REQUEST";
export const GET_PRIVATE_OFFERS_SUCCEDED = "GET_PRIVATE_OFFERS_SUCCEDED";
export const GET_PRIVATE_OFFERS_FAILED = "GET_PRIVATE_OFFERS_FAILED";

export const GET_OFFERS_REQUEST = "GET_OFFERS_REQUEST";
export const GET_OFFERS_SUCCEDED = "GET_OFFERS_SUCCEDED";
export const GET_OFFERS_FAILED = "GET_OFFERS_FAILED";
